- added patches for r82130
git-svn-id: svn://svn.code.sf.net/p/avr-llvm/code@16 ddab61f3-e77b-45cd-8477-85da285f4094

diff --git a/trunk/patches/configure.diff b/trunk/patches/configure.diff
--- a/trunk/patches/configure.diff
+++ b/trunk/patches/configure.diff
@@ -1,213 +1,213 @@
 Index: configure
 ===================================================================
---- configure	(revision 72865)
+--- configure	(revision 82136)
 +++ configure	(working copy)
-@@ -2385,6 +2385,7 @@
+@@ -2463,6 +2463,7 @@
    mips-*)                 llvm_cv_target_arch="Mips" ;;
    pic16-*)                llvm_cv_target_arch="PIC16" ;;
    xcore-*)                llvm_cv_target_arch="XCore" ;;
 +  avr-*)                  llvm_cv_target_arch="AVR" ;;
    msp430-*)               llvm_cv_target_arch="MSP430" ;;
-   *)                      llvm_cv_target_arch="Unknown" ;;
- esac
-@@ -4825,6 +4826,8 @@
+   s390x-*)                llvm_cv_target_arch="SystemZ" ;;
+   bfin-*)                 llvm_cv_target_arch="Blackfin" ;;
+@@ -4916,6 +4917,8 @@
   ;;
-     XCore)   TARGET_HAS_JIT=0
+     Blackfin)    TARGET_HAS_JIT=0
   ;;
-+    AVR)     TARGET_HAS_JIT=0
++    AVR)         TARGET_HAS_JIT=0
 + ;;
-     MSP430)  TARGET_HAS_JIT=0
+     *)           TARGET_HAS_JIT=0
   ;;
-     *)       TARGET_HAS_JIT=0
-@@ -4922,6 +4925,7 @@
-       CellSPU|SPU) TARGETS_TO_BUILD="CellSPU" ;;
-       PIC16)   TARGETS_TO_BUILD="PIC16" ;;
-       XCore)   TARGETS_TO_BUILD="XCore" ;;
-+      AVR)     TARGETS_TO_BUILD="AVR" ;;
-       MSP430)  TARGETS_TO_BUILD="MSP430" ;;
+   esac
+@@ -5013,6 +5016,7 @@
+       MSP430)      TARGETS_TO_BUILD="MSP430" ;;
+       SystemZ)     TARGETS_TO_BUILD="SystemZ" ;;
+       Blackfin)    TARGETS_TO_BUILD="Blackfin" ;;
++      AVR)         TARGETS_TO_BUILD="AVR" ;;
        *)       { { echo "$as_me:$LINENO: error: Can not set target to build" >&5
  echo "$as_me: error: Can not set target to build" >&2;}
-@@ -4941,6 +4945,7 @@
-         spu)     TARGETS_TO_BUILD="CellSPU $TARGETS_TO_BUILD" ;;
-         pic16)   TARGETS_TO_BUILD="PIC16 $TARGETS_TO_BUILD" ;;
-         xcore)   TARGETS_TO_BUILD="XCore $TARGETS_TO_BUILD" ;;
-+        avr)     TARGETS_TO_BUILD="AVR $TARGETS_TO_BUILD" ;;
-         msp430)  TARGETS_TO_BUILD="MSP430 $TARGETS_TO_BUILD" ;;
-         cbe)     TARGETS_TO_BUILD="CBackend $TARGETS_TO_BUILD" ;;
-         msil)    TARGETS_TO_BUILD="MSIL $TARGETS_TO_BUILD" ;;
-@@ -10575,7 +10580,7 @@
+    { (exit 1); exit 1; }; } ;;
+@@ -5036,6 +5040,7 @@
+         cbe)      TARGETS_TO_BUILD="CBackend $TARGETS_TO_BUILD" ;;
+         msil)     TARGETS_TO_BUILD="MSIL $TARGETS_TO_BUILD" ;;
+         cpp)      TARGETS_TO_BUILD="CppBackend $TARGETS_TO_BUILD" ;;
++        avr)      TARGETS_TO_BUILD="AVR $TARGETS_TO_BUILD" ;;
+         *) { { echo "$as_me:$LINENO: error: Unrecognized target $a_target" >&5
+ echo "$as_me: error: Unrecognized target $a_target" >&2;}
+    { (exit 1); exit 1; }; } ;;
+@@ -10972,7 +10977,7 @@
    lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
    lt_status=$lt_dlunknown
    cat > conftest.$ac_ext <<EOF
--#line 10578 "configure"
-+#line 10583 "configure"
+-#line 10975 "configure"
++#line 10980 "configure"
  #include "confdefs.h"
  
  #if HAVE_DLFCN_H
-@@ -12719,7 +12724,7 @@
+@@ -13116,7 +13121,7 @@
    ;;
  *-*-irix6*)
    # Find out which ABI we are using.
--  echo '#line 12722 "configure"' > conftest.$ac_ext
-+  echo '#line 12727 "configure"' > conftest.$ac_ext
+-  echo '#line 13119 "configure"' > conftest.$ac_ext
++  echo '#line 13124 "configure"' > conftest.$ac_ext
    if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
    (eval $ac_compile) 2>&5
    ac_status=$?
-@@ -14437,11 +14442,11 @@
+@@ -14834,11 +14839,11 @@
     -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
     -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
     -e 's:$: $lt_compiler_flag:'`
--   (eval echo "\"\$as_me:14440: $lt_compile\"" >&5)
-+   (eval echo "\"\$as_me:14445: $lt_compile\"" >&5)
+-   (eval echo "\"\$as_me:14837: $lt_compile\"" >&5)
++   (eval echo "\"\$as_me:14842: $lt_compile\"" >&5)
     (eval "$lt_compile" 2>conftest.err)
     ac_status=$?
     cat conftest.err >&5
--   echo "$as_me:14444: \$? = $ac_status" >&5
-+   echo "$as_me:14449: \$? = $ac_status" >&5
+-   echo "$as_me:14841: \$? = $ac_status" >&5
++   echo "$as_me:14846: \$? = $ac_status" >&5
     if (exit $ac_status) && test -s "$ac_outfile"; then
       # The compiler can only warn and ignore the option if not recognized
       # So say no if there are warnings other than the usual output.
-@@ -14705,11 +14710,11 @@
+@@ -15102,11 +15107,11 @@
     -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
     -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
     -e 's:$: $lt_compiler_flag:'`
--   (eval echo "\"\$as_me:14708: $lt_compile\"" >&5)
-+   (eval echo "\"\$as_me:14713: $lt_compile\"" >&5)
+-   (eval echo "\"\$as_me:15105: $lt_compile\"" >&5)
++   (eval echo "\"\$as_me:15110: $lt_compile\"" >&5)
     (eval "$lt_compile" 2>conftest.err)
     ac_status=$?
     cat conftest.err >&5
--   echo "$as_me:14712: \$? = $ac_status" >&5
-+   echo "$as_me:14717: \$? = $ac_status" >&5
+-   echo "$as_me:15109: \$? = $ac_status" >&5
++   echo "$as_me:15114: \$? = $ac_status" >&5
     if (exit $ac_status) && test -s "$ac_outfile"; then
       # The compiler can only warn and ignore the option if not recognized
       # So say no if there are warnings other than the usual output.
-@@ -14809,11 +14814,11 @@
+@@ -15206,11 +15211,11 @@
     -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
     -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
     -e 's:$: $lt_compiler_flag:'`
--   (eval echo "\"\$as_me:14812: $lt_compile\"" >&5)
-+   (eval echo "\"\$as_me:14817: $lt_compile\"" >&5)
+-   (eval echo "\"\$as_me:15209: $lt_compile\"" >&5)
++   (eval echo "\"\$as_me:15214: $lt_compile\"" >&5)
     (eval "$lt_compile" 2>out/conftest.err)
     ac_status=$?
     cat out/conftest.err >&5
--   echo "$as_me:14816: \$? = $ac_status" >&5
-+   echo "$as_me:14821: \$? = $ac_status" >&5
+-   echo "$as_me:15213: \$? = $ac_status" >&5
++   echo "$as_me:15218: \$? = $ac_status" >&5
     if (exit $ac_status) && test -s out/conftest2.$ac_objext
     then
       # The compiler can only warn and ignore the option if not recognized
-@@ -17261,7 +17266,7 @@
+@@ -17658,7 +17663,7 @@
    lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
    lt_status=$lt_dlunknown
    cat > conftest.$ac_ext <<EOF
--#line 17264 "configure"
-+#line 17269 "configure"
+-#line 17661 "configure"
++#line 17666 "configure"
  #include "confdefs.h"
  
  #if HAVE_DLFCN_H
-@@ -17361,7 +17366,7 @@
+@@ -17758,7 +17763,7 @@
    lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
    lt_status=$lt_dlunknown
    cat > conftest.$ac_ext <<EOF
--#line 17364 "configure"
-+#line 17369 "configure"
+-#line 17761 "configure"
++#line 17766 "configure"
  #include "confdefs.h"
  
  #if HAVE_DLFCN_H
-@@ -19729,11 +19734,11 @@
+@@ -20126,11 +20131,11 @@
     -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
     -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
     -e 's:$: $lt_compiler_flag:'`
--   (eval echo "\"\$as_me:19732: $lt_compile\"" >&5)
-+   (eval echo "\"\$as_me:19737: $lt_compile\"" >&5)
+-   (eval echo "\"\$as_me:20129: $lt_compile\"" >&5)
++   (eval echo "\"\$as_me:20134: $lt_compile\"" >&5)
     (eval "$lt_compile" 2>conftest.err)
     ac_status=$?
     cat conftest.err >&5
--   echo "$as_me:19736: \$? = $ac_status" >&5
-+   echo "$as_me:19741: \$? = $ac_status" >&5
+-   echo "$as_me:20133: \$? = $ac_status" >&5
++   echo "$as_me:20138: \$? = $ac_status" >&5
     if (exit $ac_status) && test -s "$ac_outfile"; then
       # The compiler can only warn and ignore the option if not recognized
       # So say no if there are warnings other than the usual output.
-@@ -19833,11 +19838,11 @@
+@@ -20230,11 +20235,11 @@
     -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
     -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
     -e 's:$: $lt_compiler_flag:'`
--   (eval echo "\"\$as_me:19836: $lt_compile\"" >&5)
-+   (eval echo "\"\$as_me:19841: $lt_compile\"" >&5)
+-   (eval echo "\"\$as_me:20233: $lt_compile\"" >&5)
++   (eval echo "\"\$as_me:20238: $lt_compile\"" >&5)
     (eval "$lt_compile" 2>out/conftest.err)
     ac_status=$?
     cat out/conftest.err >&5
--   echo "$as_me:19840: \$? = $ac_status" >&5
-+   echo "$as_me:19845: \$? = $ac_status" >&5
+-   echo "$as_me:20237: \$? = $ac_status" >&5
++   echo "$as_me:20242: \$? = $ac_status" >&5
     if (exit $ac_status) && test -s out/conftest2.$ac_objext
     then
       # The compiler can only warn and ignore the option if not recognized
-@@ -21403,11 +21408,11 @@
+@@ -21800,11 +21805,11 @@
     -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
     -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
     -e 's:$: $lt_compiler_flag:'`
--   (eval echo "\"\$as_me:21406: $lt_compile\"" >&5)
-+   (eval echo "\"\$as_me:21411: $lt_compile\"" >&5)
+-   (eval echo "\"\$as_me:21803: $lt_compile\"" >&5)
++   (eval echo "\"\$as_me:21808: $lt_compile\"" >&5)
     (eval "$lt_compile" 2>conftest.err)
     ac_status=$?
     cat conftest.err >&5
--   echo "$as_me:21410: \$? = $ac_status" >&5
-+   echo "$as_me:21415: \$? = $ac_status" >&5
+-   echo "$as_me:21807: \$? = $ac_status" >&5
++   echo "$as_me:21812: \$? = $ac_status" >&5
     if (exit $ac_status) && test -s "$ac_outfile"; then
       # The compiler can only warn and ignore the option if not recognized
       # So say no if there are warnings other than the usual output.
-@@ -21507,11 +21512,11 @@
+@@ -21904,11 +21909,11 @@
     -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
     -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
     -e 's:$: $lt_compiler_flag:'`
--   (eval echo "\"\$as_me:21510: $lt_compile\"" >&5)
-+   (eval echo "\"\$as_me:21515: $lt_compile\"" >&5)
+-   (eval echo "\"\$as_me:21907: $lt_compile\"" >&5)
++   (eval echo "\"\$as_me:21912: $lt_compile\"" >&5)
     (eval "$lt_compile" 2>out/conftest.err)
     ac_status=$?
     cat out/conftest.err >&5
--   echo "$as_me:21514: \$? = $ac_status" >&5
-+   echo "$as_me:21519: \$? = $ac_status" >&5
+-   echo "$as_me:21911: \$? = $ac_status" >&5
++   echo "$as_me:21916: \$? = $ac_status" >&5
     if (exit $ac_status) && test -s out/conftest2.$ac_objext
     then
       # The compiler can only warn and ignore the option if not recognized
-@@ -23742,11 +23747,11 @@
+@@ -24139,11 +24144,11 @@
     -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
     -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
     -e 's:$: $lt_compiler_flag:'`
--   (eval echo "\"\$as_me:23745: $lt_compile\"" >&5)
-+   (eval echo "\"\$as_me:23750: $lt_compile\"" >&5)
+-   (eval echo "\"\$as_me:24142: $lt_compile\"" >&5)
++   (eval echo "\"\$as_me:24147: $lt_compile\"" >&5)
     (eval "$lt_compile" 2>conftest.err)
     ac_status=$?
     cat conftest.err >&5
--   echo "$as_me:23749: \$? = $ac_status" >&5
-+   echo "$as_me:23754: \$? = $ac_status" >&5
+-   echo "$as_me:24146: \$? = $ac_status" >&5
++   echo "$as_me:24151: \$? = $ac_status" >&5
     if (exit $ac_status) && test -s "$ac_outfile"; then
       # The compiler can only warn and ignore the option if not recognized
       # So say no if there are warnings other than the usual output.
-@@ -24010,11 +24015,11 @@
+@@ -24407,11 +24412,11 @@
     -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
     -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
     -e 's:$: $lt_compiler_flag:'`
--   (eval echo "\"\$as_me:24013: $lt_compile\"" >&5)
-+   (eval echo "\"\$as_me:24018: $lt_compile\"" >&5)
+-   (eval echo "\"\$as_me:24410: $lt_compile\"" >&5)
++   (eval echo "\"\$as_me:24415: $lt_compile\"" >&5)
     (eval "$lt_compile" 2>conftest.err)
     ac_status=$?
     cat conftest.err >&5
--   echo "$as_me:24017: \$? = $ac_status" >&5
-+   echo "$as_me:24022: \$? = $ac_status" >&5
+-   echo "$as_me:24414: \$? = $ac_status" >&5
++   echo "$as_me:24419: \$? = $ac_status" >&5
     if (exit $ac_status) && test -s "$ac_outfile"; then
       # The compiler can only warn and ignore the option if not recognized
       # So say no if there are warnings other than the usual output.
-@@ -24114,11 +24119,11 @@
+@@ -24511,11 +24516,11 @@
     -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
     -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
     -e 's:$: $lt_compiler_flag:'`
--   (eval echo "\"\$as_me:24117: $lt_compile\"" >&5)
-+   (eval echo "\"\$as_me:24122: $lt_compile\"" >&5)
+-   (eval echo "\"\$as_me:24514: $lt_compile\"" >&5)
++   (eval echo "\"\$as_me:24519: $lt_compile\"" >&5)
     (eval "$lt_compile" 2>out/conftest.err)
     ac_status=$?
     cat out/conftest.err >&5
--   echo "$as_me:24121: \$? = $ac_status" >&5
-+   echo "$as_me:24126: \$? = $ac_status" >&5
+-   echo "$as_me:24518: \$? = $ac_status" >&5
++   echo "$as_me:24523: \$? = $ac_status" >&5
     if (exit $ac_status) && test -s out/conftest2.$ac_objext
     then
       # The compiler can only warn and ignore the option if not recognized
